### ISSUE TITLE
Error 500: There was an issue sorting files changed

### ISSUE THREAD

**Issue by JonasJacobsUserspace** [trilom/file-changes-action#104]
**Describe the bug**
Error in execution
(node:7556) UnhandledPromiseRejectionWarning: Error: {"error":"500/TypeError","from":"sortChangedFiles","message":"There was an issue sorting files changed.","payload":"{}"}
    at run (/home/runner/work/_actions/trilom/file-changes-action/v1.2.3/dist/index.js:1:19989)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:7556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
##[error]There was an issue sorting changed files from Github.
Exception: {
  "error": "500/TypeError",
  "from": "sortChangedFiles",
  "message": "There was an issue sorting files changed.",
  "payload": "{}"
}

**Workflow**
Used in a step to determine changed in files

**Expected behavior**
No errors

**Additional context**
Filesystem: 
  Ubuntu
  18.04.4
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200705.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200705.1/images/linux/Ubuntu1804-README.md

**Comment by tnightengale** [comment]
Same error.

**Comment by ghost** [comment]
```
Run trilom/file-changes-action@v1.2.3
##[error]There was an issue sorting changed files from Github.
Exception: {
  "error": "500/TypeError",
  "from": "sortChangedFiles",
  "message": "There was an issue sorting files changed.",
  "payload": "{}"
}
(node:3707) UnhandledPromiseRejectionWarning: Error: {"error":"500/TypeError","from":"sortChangedFiles","message":"There was an issue sorting files changed.","payload":"{}"}
    at run (/home/runner/work/_actions/trilom/file-changes-action/v1.2.3/dist/index.js:1:19989)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:3707) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3707) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by guitarrapc** [comment]
I've met same error with `trilom/file-changes-action@v1.2.3` and fixed on `trilom/file-changes-action@v1.2.4`.

**Comment by ghost** [comment]
no longer getting this error on trilom/file-changes-action@v1.2.4 after better specifying what PRs/pushes trigger the github action that uses this.

**Comment by gustavoplenamente** [comment]
I was facing the same issue on `v1.2.3`. Solved upgrading to `v.1.2.4` as well.
